config/routes.rb
Rails.application.routes.draw do
  post 'url_shortner/urlresult'

  get 'url_shortner/urlform'

  get 'url_shortner/retrieve'

  root 'url_shortner#urlform'

  get '/:hash', to: 'url_shortner#retrieve'

end

app/models/link.rb
class Link < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/url_shortner_controller.rb
class UrlShortnerController < ApplicationController
  def urlform
  end

  def retrieve
    hash = params[:hash]
    url = Link.find_by(url_hash: hash)
    if url == nil
      @result = "Sorry url not found. Please check you url and try again or generate a new url"
    else
      redirect_to url.url
    end
  end

  def urlresult
    url = params[:url_shortner][:url]
    hash = rand(36**7).to_s(36)
    while true
      check_hash = Link.find_by(url_hash: hash)
      if check_hash == nil
        link = Link.create(url: url, url_hash: hash)
        break
      end
    end
    @result = "#{request.headers['Host']}/#{hash}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/url_shortner_helper.rb
module UrlShortnerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Urlshortner</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/url_shortner/retrieve.html.erb
<h1>UrlShortner#retrieve</h1>
<p>Find me in app/views/url_shortner/retrieve.html.erb</p>

app/views/url_shortner/urlform.html.erb
<h1>UrlShortner</h1>
<%= form_for :url_shortner, url: url_shortner_urlresult_path do |f| %>
  <p>
  <%= f.label :url %><br>
  <%= f.text_field :url %>
  </p>

  <p>
  <%= f.submit %>
  </p>

<% end %>

app/views/url_shortner/urlresult.html.erb
<h1>Result</h1>
<p><%= @result %></p>